brew install autoconf
brew install autossh
brew install aws-sam-cli
brew install bat
brew install ca-certificates
brew install clang-format
brew install coreutils
brew install dep
brew install dos2unix
brew install entr
brew install expect
brew install fish
brew install fzf
$(brew --prefix)/opt/fzf/install
brew install gdbm
brew install gettext
brew install gh
brew install gnu-sed
brew install go
brew install goenv
brew install gowsdl
brew install helm
brew install jq
brew install kakoune
brew install kubernetes-cli
brew install libevent
brew install libidn2
brew install libtermkey
brew install libunistring
brew install libuv
brew install libvterm
brew install luajit
brew install luajit-openresty
brew install luv
brew install m4
brew install mkcert
brew install mpdecimal
brew install msgpack
brew install ncurses
brew install neovim
brew install oniguruma
brew install openssl@1.1
brew install pcre2
brew install pkg-config
brew install protobuf
brew install pstree
brew install pyenv
brew install pyenv-virtualenv
brew install python@3.8
brew install readline
brew install ripgrep
brew install sqlite
brew install starship
brew install tcl-tk
brew install tig
brew install tmux
brew install tree-sitter
brew install unibilium
brew install utf8proc
brew install vifm
brew install wget
brew install xz
brew install wkhtmltopdf
brew install nvm
brew isntall alacritty
arch -arm64 brew install kops
